// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM3Dj8aUYiUjj6kKXAF_fVxmN6x1USXYM',
    appId: '1:998439824642:web:1885aa34a17d15b14be61b',
    messagingSenderId: '998439824642',
    projectId: 'md-pro-45064',
    authDomain: 'md-pro-45064.firebaseapp.com',
    storageBucket: 'md-pro-45064.firebasestorage.app',
    measurementId: 'G-Y7FMQRTSDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPJSr-L2gFhibhBfYQ_-LVdFpVbEaBxg',
    appId: '1:998439824642:android:9ff4770112b834254be61b',
    messagingSenderId: '998439824642',
    projectId: 'md-pro-45064',
    storageBucket: 'md-pro-45064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJTLqYhvO8soQftqWLXOiTagSBu8wfLdc',
    appId: '1:998439824642:ios:bee1ba53621c34d84be61b',
    messagingSenderId: '998439824642',
    projectId: 'md-pro-45064',
    storageBucket: 'md-pro-45064.firebasestorage.app',
    iosClientId: '998439824642-j8qllja678e5vr7o2hbe3d57h1ipu0at.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJTLqYhvO8soQftqWLXOiTagSBu8wfLdc',
    appId: '1:998439824642:ios:bee1ba53621c34d84be61b',
    messagingSenderId: '998439824642',
    projectId: 'md-pro-45064',
    storageBucket: 'md-pro-45064.firebasestorage.app',
    iosClientId: '998439824642-j8qllja678e5vr7o2hbe3d57h1ipu0at.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM3Dj8aUYiUjj6kKXAF_fVxmN6x1USXYM',
    appId: '1:998439824642:web:bdbfa17d71e7a3fb4be61b',
    messagingSenderId: '998439824642',
    projectId: 'md-pro-45064',
    authDomain: 'md-pro-45064.firebaseapp.com',
    storageBucket: 'md-pro-45064.firebasestorage.app',
    measurementId: 'G-2N9FK74LYC',
  );
}
